// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_dist_to_boundary
NumericVector cpp_dist_to_boundary(NumericVector voter_lat, NumericVector voter_lon, NumericVector seg_start_lat, NumericVector seg_start_lon, NumericVector seg_end_lat, NumericVector seg_end_lon, bool show_progress);
RcppExport SEXP _Rvoterdistance_cpp_dist_to_boundary(SEXP voter_latSEXP, SEXP voter_lonSEXP, SEXP seg_start_latSEXP, SEXP seg_start_lonSEXP, SEXP seg_end_latSEXP, SEXP seg_end_lonSEXP, SEXP show_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type voter_lat(voter_latSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type voter_lon(voter_lonSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type seg_start_lat(seg_start_latSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type seg_start_lon(seg_start_lonSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type seg_end_lat(seg_end_latSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type seg_end_lon(seg_end_lonSEXP);
    Rcpp::traits::input_parameter< bool >::type show_progress(show_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_dist_to_boundary(voter_lat, voter_lon, seg_start_lat, seg_start_lon, seg_end_lat, seg_end_lon, show_progress));
    return rcpp_result_gen;
END_RCPP
}
// haversine_distance
double haversine_distance(double lat1, double lon1, double lat2, double lon2);
RcppExport SEXP _Rvoterdistance_haversine_distance(SEXP lat1SEXP, SEXP lon1SEXP, SEXP lat2SEXP, SEXP lon2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lat1(lat1SEXP);
    Rcpp::traits::input_parameter< double >::type lon1(lon1SEXP);
    Rcpp::traits::input_parameter< double >::type lat2(lat2SEXP);
    Rcpp::traits::input_parameter< double >::type lon2(lon2SEXP);
    rcpp_result_gen = Rcpp::wrap(haversine_distance(lat1, lon1, lat2, lon2));
    return rcpp_result_gen;
END_RCPP
}
// cpp_k_nearest
List cpp_k_nearest(NumericVector voter_lat, NumericVector voter_lon, NumericVector loc_lat, NumericVector loc_lon, int k, bool show_progress);
RcppExport SEXP _Rvoterdistance_cpp_k_nearest(SEXP voter_latSEXP, SEXP voter_lonSEXP, SEXP loc_latSEXP, SEXP loc_lonSEXP, SEXP kSEXP, SEXP show_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type voter_lat(voter_latSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type voter_lon(voter_lonSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type loc_lat(loc_latSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type loc_lon(loc_lonSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< bool >::type show_progress(show_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_k_nearest(voter_lat, voter_lon, loc_lat, loc_lon, k, show_progress));
    return rcpp_result_gen;
END_RCPP
}
// cpp_within_threshold
List cpp_within_threshold(NumericVector voter_lat, NumericVector voter_lon, NumericVector loc_lat, NumericVector loc_lon, double max_dist_m, bool show_progress);
RcppExport SEXP _Rvoterdistance_cpp_within_threshold(SEXP voter_latSEXP, SEXP voter_lonSEXP, SEXP loc_latSEXP, SEXP loc_lonSEXP, SEXP max_dist_mSEXP, SEXP show_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type voter_lat(voter_latSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type voter_lon(voter_lonSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type loc_lat(loc_latSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type loc_lon(loc_lonSEXP);
    Rcpp::traits::input_parameter< double >::type max_dist_m(max_dist_mSEXP);
    Rcpp::traits::input_parameter< bool >::type show_progress(show_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_within_threshold(voter_lat, voter_lon, loc_lat, loc_lon, max_dist_m, show_progress));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Rvoterdistance_cpp_dist_to_boundary", (DL_FUNC) &_Rvoterdistance_cpp_dist_to_boundary, 7},
    {"_Rvoterdistance_haversine_distance", (DL_FUNC) &_Rvoterdistance_haversine_distance, 4},
    {"_Rvoterdistance_cpp_k_nearest", (DL_FUNC) &_Rvoterdistance_cpp_k_nearest, 6},
    {"_Rvoterdistance_cpp_within_threshold", (DL_FUNC) &_Rvoterdistance_cpp_within_threshold, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_Rvoterdistance(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
