# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

haversine_distance <- function(lat1, lon1, lat2, lon2) {
    .Call(`_Rvoterdistance_haversine_distance`, lat1, lon1, lat2, lon2)
}

cpp_k_nearest <- function(voter_lat, voter_lon, loc_lat, loc_lon, k, show_progress) {
    .Call(`_Rvoterdistance_cpp_k_nearest`, voter_lat, voter_lon, loc_lat, loc_lon, k, show_progress)
}

cpp_within_threshold <- function(voter_lat, voter_lon, loc_lat, loc_lon, max_dist_m, show_progress) {
    .Call(`_Rvoterdistance_cpp_within_threshold`, voter_lat, voter_lon, loc_lat, loc_lon, max_dist_m, show_progress)
}

